---
title: "Prueba universidades externos"
output: html_document
date: "2024-11-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
libs <- c(
  'dplyr',
  'ggplot2',
  'scholar',
  'easyPubMed')

invisible(lapply(libs, library, character.only = T))
library(tidyr)
library(glue)
```

```{r}
obtener_datos <- function(id, nombre) {
  pub = get_publications(id)
  
  quitar_autor <- function(a, df) {
    df$otros_investigadores <- sapply(df$author, function(elem) {
      l <- unlist(strsplit(elem, ", ")) 
      aux2 <- l[!grepl(a, l)]
      return(paste(aux2, collapse = ";"))
    })
    
    # Eliminar la columna 'author' del data frame
    df <- df[, !names(df) %in% "author"]
    
    return(df)
  }
  
  dfr <- quitar_autor(nombre, pub)
  
  cols_to_remove <- c("author", "number", "cites", "cid", "pubid")
  dfr <- dfr[, !(names(dfr) %in% cols_to_remove)]

  write.csv(dfr, paste0("datos_finales_GS_", nombre, ".csv"), row.names = FALSE)
}
```

```{r}
obtener_datos("rzmpFawAAAAJ&hl", "MGS")
```

