import pandas as pd

def crear_one_hot_excel(diccionario, nombre_archivo):
    palabras_unicas = set()
    for valor in diccionario.values():
        palabras_unicas.update(valor.replace(', ', ',').split(','))

    columnas = sorted(list(palabras_unicas))

    filas_de_datos = []
    for clave, valor in diccionario.items():
        fila = {palabra: 0 for palabra in columnas}
        palabras_en_valor = valor.replace(', ', ',').split(',')
        for palabra in palabras_en_valor:
            if palabra in fila:
                fila[palabra] = 1
        fila['-'] = clave
        filas_de_datos.append(fila)

    df = pd.DataFrame(filas_de_datos)
    df = df[['-'] + columnas]

    df.to_excel(nombre_archivo, index=False)

    print(f"Archivo '{nombre_archivo}' creado exitosamente.")


dic = {
    "NaN":"",
    "Conferencia":"",
    "No indexada":"",
    "AIP Advances":"physics, experimental, theoretical, applied, materials, chemistry, engineering, biophysics, optoelectronics, nanotechnology",
    "AIMS Mathematics":"mathematics, research, original, expository, theory, applied, statistics, numbertheory, analysis, openaccess",
    "APL Materials":"materials, experimental, bioinspired, nanotechnology, photovoltaics, magnets, tissue engineering, optoelectronics, condensedmatter, theory",
    "ASME International Mechanical Engineering Congress and Exposition":"mechanical, engineering, research, energy, manufacturing, digitalization, mobility, innovation, systems, industry",
    "ATOMKI Annual Report":"nuclear, atomic, particle, research, experimental, physics, institute, report, fundamental, applied",
    "Abstract and Applied Analysis":"analysis, applied, classical, functional, differential, optimization, control, nonlinear, linear, theory",
    "Acoustic Metamaterials: Absorption Cloaking Imaging Time Modulated Media":"acoustic, metamaterials, absorption, cloaking, imaging, modulation, sound, wave, manipulation, advanced",
    "Acoustic waves in periodic structures metamaterials and porous media: from":"acoustic, waves, periodic, metamaterials, porous, propagation, modeling, media, fundamentals, applications",
    "Acoustics":"acoustics, science, engineering, interdisciplinary, sound, research, peerreview, projects, analysis, forum",
    "Acta Acustica united with Acustica":"acoustics, review, scientific, applied, technical, engineering, research, communications, journal, audio",
    "Acta Applicandae Mathematicae":"mathematics, applied, theory, analysis, research, journal, applications, pure, modeling, equations",
    "Acta Astronautica":"space, astronautics, research, engineering, aerospace, vehicles, propulsion, orbital, systems, technology",
    "Acta Mathematica Hungarica":"mathematics, hungarian, pure, research, journal, theory, analysis, geometry, algebra, functional",
    "Acta Mathematica Sinica English Series":"mathematics, pure, applied, research, journal, theory, science, analysis, international, institute",
    "Acta Sci. Math.(Szeged)":"mathematics, research, hungary, journal, pure, analysis, theory, geometry, algebra, topology",
    "Advanced Concepts for Intelligent Vision Systems:":"vision, intelligent, video, segmentation, classification, biometrics, deep, restoration, analysis, compression",
    "Advanced Materials Technologies":"materials, technology, nanotechnology, optoelectronics, composites, chemical, 3d, printing, flexible, electronics",
    "Advanced Optical Materials":"optical, materials, photonics, plasmonics, metamaterials, nanostructures, optoelectronics, holography, waveguides, devices",
    "Advanced Photonics Research":"photonics, optics, materials, optoelectronics, magnetic, research, openaccess, fundamental, applied, innovation",
    "Advances in Algebra":"algebra, theoretical, applied, research, international, journal, structure, groups, fields, rings",
    "Advances in Differential Equations and Applications":"differential, equations, mathematics, analysis, nonlinear, control, ordinary, partial, applications, fractional",
    "Advances in Mathematics":"mathematics, pure, research, theory, advances, journal, contributions, specialists, community, important",
    "Advances in Microlocal and Time-Frequency Analysis":"microlocal, time, frequency, analysis, signal, processing, harmonic, mathematics, conference, contributions",
    "Advances in Operator Theory":"operator, theory, functional, analysis, mathematics, research, journal, functionalanalysis, operators, functional",
    "Advances in applied Clifford algebras":"clifford, algebras, mathematics, applications, functional, physics, engineering, survey, research, geometry",
    "Advances in the Theory of Frechet Spaces":"spaces, topology, functional, analysis, theory, research, mathematics, frechet, infinite, Banach",
    "Aequationes mathematicae":"functional, equations, dynamics, combinatorics, geometry, research, journal, systems, mathematics, equations",
    "Aerospace Science and Technology":"aerospace, aerodynamics, propulsion, materials, avionics, structures, navigation, control, robotics, acoustics",
    "Algal Research":"algae, biotechnology, biofuel, cultivation, ecology, biomass, molecular, genetics, environment, processing",
    "Algebra Colloquium":"algebra, theory, structure, groups, rings, fields, combinatorics, geometry, research, applications",
    "Algebra and Discrete Mathematics":"algebra, discrete, combinatorics, logic, graph, theory, research, finite, structures, applications",
    "Algorithms":"algorithms, design, analysis, experiments, optimization, complexity, applications, computing, openaccess, methods",
    "American Institute of Mathematical Sciences":"mathematics, applied, pure, analysis, statistics, research, modeling, theoretical, education, journal",
    "American Institute of Physics":"physics, research, education, publications, standards, community, resources, institutions, outreach, development",
    "American Mathematical Society":"mathematics, research, education, publications, conferences, professional, community, journals, outreach, standards",
    "American Nuclear Society":"nuclear, energy, radiation, reactors, safety, materials, research, technology, engineering, policy",
    "American Physical Society":"physics, research, education, conferences, publications, community, outreach, standards, professional, advocacy",
    "Anales de ASEPUMA":"mathematics, applied, technology, education, research, teaching, university, association, publication, applications",
    "Anales de Documentacion":"documentation, librarianship, archives, information, preservation, management, digitization, libraries, theory, practice",
    "Anales de Fisica":"physics, research, experimental, theoretical, nuclear, particle, optics, condensedmatter, applications, Spanish",
    "Anales de Pediatria":"pediatrics, child, medicine, clinical, health, diagnosis, treatment, research, pediatric, care",
    "Anals de la Real Academia de Cultura Valenciana":"culture, Valencian, history, literature, art, scholarship, heritage, academy, regional, studies",
    "Analysis & PDE":"analysis, PDE, differential, equations, partial, research, theory, mathematics, applied, methods",
    "Analysis and Applications":"analysis, applied, mathematical, physical, biological, engineering, techniques, differential, integral, optimization",
    "Analysis and Mathematical Physics":"analysis, mathematical, physics, theoretical, research, equations, models, applied, dynamics, structures",
    "Annales Fennici Mathematici":"mathematics, research, Finnish, analysis, geometry, algebra, theory, journal, pure, applied",
    "Annales de l Institut Fourier":"analysis, geometry, Fourier, mathematical, spectral, research, theory, dynamics, functions, topology",
    "Annali di Matematica Pura ed Applicata":"mathematics, pure, applied, theory, research, applications, analysis, algebra, geometry, modelling",
    "Annals of Emergency Medicine":"emergency, medicine, clinical, research, treatment, diagnosis, teaching, patient, care, international",
    "Annals of Operations Research":"operations, research, optimization, algorithms, modeling, applied, theory, logistics, decision, analysis",
    "Anuario ThinkEPI":"education, annual, publication, research, analysis, academic, technology, policy, interdisciplinary, report",
    "Applicable Algebra in Engineering Communication and Computing":"algebra, engineering, communication, computing, applied, structures, theory, coding, cryptography, modeling",
    "Applications of Fuzzy Sets Theory:":"fuzzy, sets, theory, applications, logic, uncertainty, control, systems, modeling, mathematics",
    "Applied Acoustics":"acoustics, applied, sound, noise, vibration, engineering, modeling, measurements, analysis, systems",
    "Applied General Topology":"topology, applied, general, structures, continuity, compactness, research, theory, functions, spaces",
    "Applied Mathematical Modelling":"mathematics, applied, modelling, simulation, dynamics, engineering, systems, research, analysis, optimization",
    "Applied Mathematics & Information Sciences":"mathematics, applied, information, systems, data, modeling, computational, analysis, engineering, science",
    "Applied Mathematics Letters":"mathematics, applied, letters, brief, theory, analysis, research, applications, short, communication",
    "Applied Mathematics and Computation":"mathematics, applied, computation, numerical, analysis, algorithms, modeling, simulation, methods, systems",
    "Applied Mathematics and Nonlinear Sciences":"mathematics, applied, nonlinear, dynamics, modeling, systems, theory, analysis, chaos, research",
    "Applied Physics Letters":"physics, applied, letters, short, research, experimental, materials, optics, nanophysics, electronics",
    "Applied Sciences":"science, applied, engineering, technology, research, environmental, materials, health, data, modeling",
    "Applied and Computational Harmonic Analysis":"analysis, harmonic, computational, applied, theoretical, methods, algorithms, information, processing, interdisciplinary",
    "Applied mathematical sciences":"mathematics, applied, science, engineering, economics, business, computing, industry, methods, modeling",
    "Applied physics express":"applied, physics, letters, rapid, concise, novel, research, timely, dissemination, high-impact",
    "Aquilafuente":"culture, regional, history, local, heritage, community, research, tradition, heritage, society",
    "Arbeitspapiere der FOM":"workingpapers, FOM, business, research, education, management, economics, academia, reports, professional",
    "Arbor":"culture, humanities, social, thought, science, reflection, debate, Spanish, openaccess, society",
    "Archiv der Mathematik":"mathematics, research, short, general, high-quality, broad, accessible, concise, papers, pure",
    "Archives of Acoustics":"acoustics, physiological, psychoacoustics, speech, environmental, noise, vibration, music, instrumentation, bioacoustics",
    "Archives of budo":"sports, martial, arts, combat, biomechanics, kinesiology, training, performance, interdisciplinary, research",
    "Artificial Intelligence in Medicine":"artificial, intelligence, medicine, healthcare, diagnostic, predictive, models, clinical, decision, research",
    "Arxiv preprint arXiv:":"preprint, repository, openaccess, preliminary, research, multidisciplinary, physics, mathematics, computing, dissemination",
    "Banach Journal Of Mathematical Analysis":"analysis, functional, operator, Banach, harmonic, theory, spaces, operator, research, survey",
    "Bid Textos Universitaris de Biblioteconomia I Documentacio":"library, science, documentation, biblioteconomy, university, academic, research, cataloging, information, education",
    "Biotechnology journal":"biotechnology, genetic, molecular, bioprocess, engineering, software, computational, bioprocessing, research, applications",
    "Bolema: Boletim de Educacao Matematica":"mathematics, education, teaching, pedagogy, research, Brazilian, journal, learning, curriculum, training",
    "Boletin de la ANABAD":"archives, libraries, documentation, Spain, professional, research, librarianship, history, preservation, publication",
    "Boletin de la Asociacion Andaluza de Bibliotecarios":"libraries, Andalusia, bibliothek, librarianship, documentation, research, professional, regional, publication, Spanish",
    "Boletin de la Sociedad Cubana de Matematica y Computacion":"mathematics, computing, Cuba, research, journal, theory, algorithms, applied, community, education",
    "Boletin de la Sociedad Matematica Mexicana: Tercera Serie":"mathematics, Mexico, research, theory, journal, analysis, algebra, geometry, education, applications",
    "Boletin de la Sociedad Mexicana de Fisica":"physics, Mexico, research, theoretical, experimental, journal, education, community, applications, science",
    "Bollettino dell Unione Matematica Italiana":"mathematics, Italy, research, theory, pure, applied, journal, education, analysis, geometry",
    "Buildings":"architecture, engineering, buildings, design, construction, materials, energy, management, sustainability, structures",
    "Bull. Pol. Acad. Sci. Math":"mathematics, concise, research, allareas, English, peerreview, correctness, novelty, editorial, Poland",
    "Bull. Soc. Roy. Sci. Liege":"multidisciplinary, physics, chemistry, biology, geology, mathematics, mineralogy, natural, research, Belgium",
    "Bulletin de la Societe Royale des Sciences de Liege":"multidisciplinary, physics, chemistry, biology, geology, mathematics, mineralogy, natural, research, Belgium",
    "Bulletin des sciences mathematiques":"mathematics, research, theory, applied, pure, journal, analysis, algebra, geometry, concise",
    "Bulletin of the American Mathematical Society":"survey, mathematics, accessible, nonexperts, reviews, perspectives, research, contemporary, AMS, quarterly",
    "Bulletin of the Australian Mathematical Society":"mathematics, research, Australia, society, journal, theory, pure, applied, community, education",
    "Bulletin of the Belgian Mathematical Society Simon Stevin":"mathematics, Belgium, society, research, theory, pure, applied, journal, community, Belgian",
    "Bulletin of the Brazilian Mathematical Society New Series":"mathematics, Brazil, society, research, theory, pure, applied, journal, community, Brazilian",
    "Bulletin of the London Mathematical Society":"mathematics, London, society, research, theory, pure, applied, journal, community, English",
    "Bulletin of the Malaysian Mathematical Sciences Society":"mathematics, Malaysia, society, research, theory, pure, applied, journal, community, Malaysian",
    "CEUR workshop proceedings. Proceedings of the":"CEUR, workshop, proceedings, openaccess, computer, science, conference, papers, rapid, dissemination",
    "CRC Press":"publisher, academic, books, science, engineering, mathematics, technical, research, education, general",
    "CUADERNOS DE TURISMO":"tourism, Spanish, research, hospitality, tourismindustry, education, management, study, article, journal",
    "Cambridge University Press":"publisher, academic, books, journals, research, education, global, Cambridge, multidisciplinary, scholarship",
    "Canadian Mathematical Bulletin":"mathematics, concise, research, generalinterest, Canada, CanadaMS, quarterly, journal, theory, analysis",
    "Central European Journal of Mathematics":"mathematics, research, international, allfields, pure, applied, geometry, analysis, theory, algebra",
    "Centro de Investigacion Operativa Universidad Miguel Hernandez de Elche":"operations, research, optimization, university, Elche, modeling, logistics, systems, analysis, applied",
    "Ch. the Transfer Matrix Method in Acoustics Springer International":"acoustics, transfer, matrix, method, wave, propagation, modeling, physics, analysis, engineering",
    "Chaos Solitons & Fractals":"nonlinear, dynamics, chaos, solitons, fractals, complexity, networks, mathematical, analysis, applied",
    "Chaos: An Interdisciplinary Journal of Nonlinear Science":"nonlinear, dynamics, chaos, solitons, fractals, complexity, networks, mathematical, analysis, applied",
    "Chinese Journal of Physics":"physics, statistical, biophysics, condensed, optics, particles, nuclear, chaos, astrophysics, quantum",
    "Circulo de Linguistica Aplicada a la Comunicacion":"linguistics, applied, communication, linguisticscircle, language, research, discourse, education, analysis, media",
    "Classical and Quantum Gravity":"gravity, relativity, spacetime, cosmology, quantum, mathematical, general, experimental, superstrings, gravitation",
    "Collectanea Mathematica":"mathematics, research, Spain, pure, applied, original, analysis, geometry, algebra, journal",
    "Color Image and Video Enhancement":"color, image, video, enhancement, processing, computer, visual, quality, algorithms, simulation",
    "Commentarii Mathematici Helvetici":"mathematics, research, Switzerland, quarterly, pure, analysis, theory, journal, geometry, algebra",
    "Communications in Algebra":"algebra, theory, rings, modules, structure, homological, commutative, noncommutative, research, journal",
    "Communications on Pure & Applied Analysis":"analysis, pure, applied, functional, differential, integral, theory, research, journal, methods",
    "Complex Analysis and Operator Theory":"complex, analysis, operator, theory, functional, holomorphic, spectrum, research, mathematics, journal",
    "Comptes Rendus Mathematique":"mathematics, research, rapid, notes, French, bulletin, pure, applied, geometry, analysis",
    "Comptes Rendus de l'Academie des Sciences Serie I - Mathematique":"mathematics, algebra, analysis, geometry, logic, probability, applied, original, rapid, France",
    "Comptes Rendus. Physique":"physics, optics, astrophysics, particles, rapid, French, applied, phenomena, academic, journal",
    "Computational Optimization and Applications":"optimization, computational, mathematics, algorithms, modeling, stochastic, deterministic, experiments, applications, theory",
    "Computer Applications in Engineering Education":"computer, engineering, education, simulation, teaching, modeling, training, research, software, tools",
    "Computer Networks":"networks, computer, communications, internet, protocols, security, distributed, wireless, IoT, connectivity",
    "Computer Physics Communications":"computational, physics, software, numerical, methodology, codes, hardware, analysis, implementation, communication",
    "Computer Vision and Image Understanding":"computer, vision, image, understanding, recognition, processing, features, detection, algorithms, scenes",
    "Computer methods and programs in biomedicine":"computer, biomedicine, methods, programs, modeling, medical, simulation, analysis, applications, healthcare",
    "Computers":"computers, systems, software, hardware, computing, research, technology, applications, computing, development",
    "Computers & Mathematics with Applications":"computers, mathematics, applications, modeling, simulation, analysis, methods, systems, applied, computational",
    "Computers & Operations Research":"computers, operations, research, optimization, modeling, simulation, logistics, systems, analysis, algorithms",
    "Computers & Structures":"computers, structures, engineering, modeling, analysis, simulation, design, mechanics, construction, systems",
    "Computing Letters":"computing, letters, short, research, concise, methods, reports, computer, science, communication",
    "ConCIENCIAS. digital: revista de divulgacion cientifica de las Facultad de":"science, digital, dissemination, divulgation, education, outreach, interdisciplinary, journal, research, communication",
    "Condensed Matter":"condensed, matter, physics, materials, solid, states, properties, research, experimental, theoretical",
    "Conferencias y Comunicaciones de EuroRegio":"conference, regional, EuroRegion, communication, collaboration, crossborder, presentations, research, cooperation, development",
    "Congres Francais d'Acoustique":"acoustics, conference, French, research, sound, engineering, perception, music, environment, theory",
    "Congreso Bienal de la Real Sociedad Matematica Espanola":"mathematics, conference, biennial, Spain, research, collaboration, presentations, plenary, community, developments",
    "Consejo Superior de Investigaciones Cientificas (Espana)":"CSIC, research, Spain, science, publications, openaccess, institutional, technology, policy, journals",
    "Contemporary Mathematics":"mathematics, theoretical, numerical, experimental, algebra, geometry, topology, analysis, applied, physics",
    "Contributions to Plasma Physics":"plasma, physics, experimental, theoretical, lowtemperature, diagnostics, dusty, discharges, surface, medicine",
    "Convergencia":"social, communication, controversies, political, sociology, LatinAmerica, research, case studies, administration, theory",
    "Critical reviews in biotechnology":"biotechnology, review, fermentation, genetic, techniques, fuel, waste, evaluation, industrial, methodology",
    "Crystals":"crystallography, growth, characterization, materials, optical, magnetic, semiconductors, photonic, biominerals, processing",
    "Cuadernos de Administracion":"administration, management, business, organization, research, education, strategy, policy, journals, theory",
    "Cuestiones Pedagogicas. Revista de Ciencias de la Educacion":"education, pedagogy, teaching, research, learning, curriculum, theory, school, teacher, journal",
    "Cuestiones pedagogicas":"education, pedagogy, teaching, research, learning, curriculum, theory, school, teacher, journal",
    "Czechoslovak Mathematical Journal":"mathematics, research, Czech, Slovak, pure, applied, analysis, algebra, geometry, theory",
    "DYNA":"engineering, industrial, Spain, research, applications, technology, systems, journal, development, professionalism",
    "Data":"data, analytics, statistics, information, research, dataset, analysis, methodology, computing, science",
    "Department of Mathematics and Statistics University of Helsinki":"mathematics, statistics, research, Helsinki, department, university, teaching, analysis, modelling, academia",
    "Descriptive Topology and Functional Analysis":"topology, descriptive, functional, analysis, mathematics, research, spaces, continuity, properties, theory",
    "Descriptive Topology and Functional Analysis II":"topology, descriptive, functional, analysis, mathematics, continuation, advanced, research, spaces, theory",
    "Digital CSIC":"digital, CSIC, repository, Spain, research, publications, openaccess, institutional, science, archive",
    "Digital Scholarship in the Humanities":"digital, humanities, computing, linguistics, methodology, research, literature, language, review, technology",
    "Direccion Y Organizacion":"management, organization, strategy, business, research, education, administration, decisionmaking, leadership, journal",
    "Direct and Large Eddy Simulation XII":"simulation, direct, eddy, computational, fluid, turbulence, modeling, numerical, research, conference",
    "Discrete and Continuous Dynamical Systems":"dynamics, discrete, continuous, systems, mathematics, chaos, stability, modeling, theory, research",
    "Designs codes and cryptography":"design, codes, cryptography, algebraic, geometric, discrete, finitefields, coding, security, theory",
    "Displays":"displays, screens, technology, imaging, research, hardware, visual, development, electronics, innovation",
    "Dissertationes mathematicae":"dissertations, mathematics, doctoral, research, theory, analysis, pure, applied, journal, thesis",
    "Divulgaciones Matematicas":"mathematics, outreach, education, communication, popularization, research, teaching, learning, journal, divulgation",
    "Documenta Mathematica":"mathematics, research, original, articles, theory, analysis, geometry, algebra, peerreview, journal",
    "Doklady Mathematics":"mathematics, notes, short, results, Russian, rapid, research, theory, announcements, peerreview",
    "ECTS Assessment in Higher Education (ISBN:":"assessment, ECTS, education, higher, highereducation, accreditation, policy, teaching, evaluation, standards",
    "EDULEARN":"education, learning, conference, technology, innovation, teaching, research, digital, pedagogy, development",
    "EPI El Profesional de la informacion":"information, documentation, professionals, research, libraries, knowledge, management, digital, communication, journal",
    "ETFA":"automation, industrial, factory, emerging, technologies, engineering, research, systems, innovation, conference",
    "EURO Journal on Computational Optimization":"optimization, computational, operations, research, computer, modeling, algorithms, applications, experiments, OR",
    "Ecological Informatics":"ecology, computational, data, biogeography, informatics, ecosystem, sustainability, environment, AI, analysis",
    "Econometrics":"econometrics, modeling, forecasting, econometric, theory, openaccess, empirical, statistics, research, methodology",
    "Economia Agraria y Recursos Naturales":"agricultural, economics, resources, rural, development, environment, Spain, food, policy, research",
    "Ediciones Universidad de Salamanca":"publisher, academic, books, journals, research, education, Spain, university, scholarly, publications",
    "Editorial Club Universitario":"publisher, academic, university, publications, books, education, Spain, research, scholarly, editorial",
    "Educacion Medica":"medical, education, training, research, clinical, teaching, health, curriculum, journal, pedagogy",
    "El Profesional de la Informacion":"information, documentation, professionals, libraries, knowledge, management, research, communication, digital, journal",
    "Electronic Notes in Discrete Mathematics":"electronics, notes, discrete, mathematics, proceedings, rapid, conference, digital, research, combinatorics",
    "Electronic Notes in Theoretical Computer Science":"electronics, notes, theoretical, computer, science, proceedings, rapid, conference, algorithms, research",
    "Electronics":"electronics, technology, hardware, circuits, research, devices, engineering, innovation, semiconductors, applications",
    "Encuentros multidisciplinares":"multidisciplinary, meetings, research, collaboration, dialogue, academic, forum, interdisciplinary, conference, studies",
    "Engineering Structures":"engineering, structures, design, analysis, mechanics, construction, simulation, modeling, research, buildings",
    "Energies":"energy, power, renewable, systems, sustainability, research, engineering, solar, wind, efficiency",
    "Engineering Proceedings":"engineering, proceedings, conference, technology, innovation, research, systems, development, design, applications",
    "Ensayos: Revista de la Facultad de Educacion de Albacete":"education, teaching, research, learning, pedagogy, curriculum, school, training, Spain, university",
    "Ensenanza de las ciencias: revista de investigacion y experiencias":"science, teaching, education, learning, research, didactics, curriculum, methodology, school, pedagogy",
    "Enterpreneurship and Sustainability Issues":"entrepreneurship, sustainability, innovation, business, economics, management, growth, research, issues, policy",
    "Entropy":"entropy, information, physics, thermodynamics, complexity, systems, nonlinear, statistical, mathematics, theory",
    "Environmental Engineering and Management Journal":"environmental, engineering, management, pollution, waste, water, sustainability, research, energy, treatment",
    "Epsilon":"mathematics, education, teaching, Spain, research, learning, pedagogy, didactics, school, training",
    "Ergodic Theory and Dynamical Systems":"ergodic, theory, dynamical, systems, mathematics, probability, measure, topology, chaos, analysis",
    "Espana. Ministerio de Cultura. Subdireccion General de Publicaciones":"Spain, ministry, culture, publications, government, research, heritage, books, journals, editorial",
    "Estableciendo puentes en una economia global. Escuela Superior de Gestion":"economy, global, management, business, bridges, research, conference, international, development, education",
    "Estudios DE Economia Aplicada":"economics, applied, research, Spain, policy, business, development, finance, growth, management",
    "Estudios Turisticos":"tourism, studies, Spain, economics, research, hospitality, policy, travel, management, culture",
    "European Journal of Clinical Microbiology and Infectious Diseases":"microbiology, clinical, infectious, diseases, medicine, research, diagnostics, therapy, epidemiology, pathogens",
    "European Journal of Engineering Education":"engineering, education, teaching, learning, students, curriculum, pedagogy, research, training, Europe",
    "European Journal of Operational Research":"operations, research, optimization, decision, modeling, systems, algorithms, logistics, management, applied",
    "European journal of cancer":"cancer, oncology, clinical, research, therapy, treatment, biology, genetics, diagnosis, epidemiology",
    "European journal of physics":"physics, education, teaching, research, experiments, students, learning, pedagogy, methods, theory",
    "Europhysics Letters":"physics, letters, rapid, communication, research, condensed, matter, optics, statistical, interdisciplinary",
    "Evolution Equations and Control Theory (Online)":"evolution, equations, control, theory, mathematics, dynamics, systems, analysis, stability, applied",
    "Experimental Mathematics":"experimental, mathematics, computation, algorithms, conjectures, research, numerical, symbolic, visualization, analysis",
    "Expert Systems":"expert, systems, artificial, intelligence, knowledge, reasoning, decision, research, computer, applications",
    "Expert Systems with Applications":"expert, systems, applications, artificial, intelligence, machinelearning, decision, data, analysis, computing",
    "Extracta mathematicae":"mathematics, research, Spain, pure, applied, analysis, geometry, algebra, theory, journal",
    "FMC Formacion Medica Continuada en Atencion Primaria":"medical, training, continuous, education, primary, healthcare, clinical, practice, research, Spain",
    "Figshare":"repository, digital, data, sharing, openaccess, science, research, publications, archive, platform",
    "Filomat":"mathematics, research, journal, analysis, algebra, geometry, applied, pure, theory, Serbia",
    "Finance Markets and Valuation":"finance, markets, valuation, economics, marketing, management, legislation, research, openaccess, investment",
    "Fixed Point Theory and Applications":"fixedpoint, theory, applications, mathematics, topology, analysis, nonlinear, methods, economics, geometry",
    "Florida Ediciones":"publisher, academic, books, journals, research, education, Florida, publications, scholarly, editorial",
    "Food Biophysics":"food, biophysics, physical, structure, molecular, research, properties, systems, analysis, nutrition",
    "Food and Agriculture":"food, agriculture, production, farming, sustainability, crops, research, environment, rural, policy",
    "Fortschritte der Physik":"physics, advances, German, research, theory, experimental, review, developments, journal, science",
    "Foundations of Physics":"physics, foundations, theory, quantum, relativity, information, space, time, principles, research",
    "Freie Univ. Fachbereich Mathematik und Informatik":"mathematics, computer, science, teaching, research, Berlin, department, university, modeling, statistics",
    "Frontiers in Optics":"optics, light, photonics, research, conference, imaging, lasers, systems, technology, innovation",
    "Frontiers in Psychology":"psychology, research, openaccess, cognition, behavior, neuroscience, social, developmental, clinical, articles",
    "Frontiers in Public Health":"publichealth, research, openaccess, epidemiology, disease, policy, prevention, population, health, journals",
    "Frontiers Media SA":"publisher, openaccess, research, science, journals, multidisciplinary, Frontiers, peerreview, platform, publications",
    "Funct. Approx. Comment. Math":"functional, approximation, mathematics, analysis, theory, research, pure, applied, journal, methods",
    "Functional Analysis":"functional, analysis, mathematics, spaces, operators, research, theory, linear, norms, topology",
    "Functiones et Approximatio Commentarii Mathematici":"functional, approximation, mathematics, analysis, theory, research, pure, applied, journal, methods",
    "Fuzzy Sets and Systems":"fuzzy, sets, systems, logic, uncertainty, modeling, theory, applications, research, mathematics",
    "Gaceta de la Real Sociedad Matematica Espanola":"mathematics, Spain, society, research, education, journal, bulletin, community, RSME, outreach",
    "Gender Technology and Development":"gender, technology, development, equality, society, research, policy, empowerment, innovation, studies",
    "General Topology in Banach Spaces Nova Sci. Publ. Huntington":"topology, Banach, spaces, geometry, analysis, functional, pure, topology, research, theory",
    "Georgia Institute of Technology":"engineering, research, technology, GeorgiaTech, innovation, education, computing, science, development, institute",
    "Geometriae Dedicata":"geometry, mathematics, research, differential, algebraic, topology, theory, analysis, journal, geometry",
    "Geothermics":"geothermal, energy, heat, earth, research, system, renewable, subsurface, environment, applied",
    "Glas. Mat":"mathematics, research, analysis, algebra, geometry, theory, journal, pure, applied, Scotland",
    "Glasgow Mathematical Journal":"mathematics, research, pure, applied, algebra, analysis, geometry, theory, number, topology",
    "Graefe's Archive for Clinical and Experimental Ophthalmology":"ophthalmology, clinical, experimental, vision, research, retina, surgery, imaging, glaucoma, ophthalmic",
    "Grey Journal (TGJ):":"grey, literature, information, openaccess, policy, reports, repository, librarians, digital, research",
    "HVAC&R Research":"HVAC, heating, ventilation, airconditioning, refrigeration, systems, energy, building, simulation, research",
    "Hacettepe University":"Hacettepe, University, research, education, Turkey, academic, faculty, teaching, science, students",
    "Health Informatics Journal":"health, informatics, systems, data, medical, digital, research, clinical, analytics, technology",
    "Hipertext. net":"hypertext, web, hypermedia, research, technology, digital, network, communication, information, design",
    "Houston J. Math":"mathematics, research, Houston, pure, applied, analysis, algebra, geometry, number, journal",
    "Icarus":"planetary, science, astronomy, moons, satellites, research, solar, system, geology, atmosphere",
    "IEEE Access":"IEEE, openaccess, multidisciplinary, engineering, technology, research, rapid, publishing, articles, computing",
    "IEEE Computer Society":"IEEE, computer, society, standards, research, publishing, conferences, computing, education, technology",
    "IEEE EDUCON":"education, computing, IEEE, conference, technology, research, engineering, learning, teaching, innovation",
    "IEEE Revista Iberoamericana de Tecnologias del Aprendizaje":"IEEE, learning, technologies, education, Iberoamericana, research, teaching, digital, innovation, LatinAmerica",
    "IEEE Sensors Journal":"sensors, IEEE, measurement, devices, signal, research, application, technology, systems, data",
    "IEEE Transactions on Fuzzy Systems":"fuzzy, systems, IEEE, logic, uncertainty, modeling, control, research, theory, applications",
    "IEEE Transactions on Image Processing":"image, processing, IEEE, algorithms, vision, filtering, compression, enhancement, research, computing",
    "IEEE Transactions on Industry Applications":"industry, applications, IEEE, engineering, electrical, controls, systems, research, power, technology",
    "IET Image Processing":"image, processing, IET, algorithms, enhancement, filtering, recognition, systems, vision, research",
    "IET Synthetic Biology":"synthetic, biology, IET, research, engineering, systems, genetic, modeling, biotechnology, design",
    "IJCAI":"AI, conference, artificial, intelligence, research, international, computing, learning, applications, algorithms",
    "INFORMS Inst.for Operations Res.and the Management Sciences":"operations, research, management, optimization, analytics, decision, modeling, business, OR, society",
    "IOP Publishing":"physics, publishing, journals, research, science, IOP, society, academic, openaccess, institute",
    "ISKO":"knowledge, organization, society, information, classification, ontology, indexing, research, library, systems",
    "ISTE Limited":"publishing, academic, ISTE, technology, research, books, education, engineering, science, digital",
    "Illinois Journal of Mathematics":"mathematics, Illinois, research, analysis, algebra, geometry, topology, number, theory, journal",
    "Image Analysis:":"image, analysis, processing, recognition, algorithms, vision, features, computer, systems, research",
    "Image and Vision Computing":"image, vision, computing, recognition, processing, algorithms, graphics, features, research, systems",
    "Indagationes Mathematicae":"mathematics, research, Netherlands, pure, applied, algebra, analysis, geometry, theory, journal",
    "Indice: Revista de Estadistica y Sociedad":"statistics, society, Spain, research, data, analysis, demographic, methodology, social, journal",
    "Informatics for Health and Social Care":"informatics, health, care, social, systems, data, digital, medical, research, technology",
    "Information":"information, data, systems, digital, knowledge, computing, communication, research, theory, openaccess",
    "Information Research":"information, research, digital, knowledge, retrieval, library, communication, systems, science, electronic",
    "Information Sciences":"information, sciences, systems, data, computing, intelligence, research, communication, knowledge, networks",
    "Information research an international electronic journal":"information, electronic, journal, research, retrieval, systems, digital, library, communication, access",
    "Innovacion educativa":"education, innovation, teaching, learning, research, curriculum, pedagogy, digital, methodology, school",
    "Innovar":"innovation, business, management, economics, research, entrepreneurship, policy, strategy, education, LatinAmerica",
    "Instituto Universitario de Ciencias Politicas y Sociales. Universidad de La":"politics, social, sciences, research, university, Spain, governance, society, education, policy",
    "Instituto Universitario de Matematica Pura y Aplicada Universitat ...":"mathematics, pure, applied, research, university, Spain, IUMPA, analysis, algebra, geometry",
    "Integral Equations and Operator Theory":"integral, equations, operator, theory, mathematics, functional, analysis, spaces, research, journal",
    "Intellectual economics":"economics, intellectual, research, management, business, innovation, knowledge, society, finance, theory",
    "Interfaces and Free Boundaries":"interfaces, free, boundaries, mathematics, analysis, geometry, PDE, theory, research, applications",
    "International Institute of Informatics and Systemics IIIS":"informatics, systemics, international, research, systems, conference, institute, multidisciplinary, computing, society",
    "International Journ Engineering Intelligent Systems Electrical Engineering ...":"engineering, intelligent, systems, electrical, computing, research, applications, algorithms, automation, journal",
    "International Journal of Applied Ceramic Technology":"ceramics, technology, applied, materials, processing, engineering, research, properties, manufacturing, science",
    "International Journal of Bifurcation and Chaos":"bifurcation, chaos, nonlinear, dynamics, systems, complexity, mathematics, modeling, analysis, research",
    "International Journal of Business Performance and Supply Chain Modelling":"business, performance, supplychain, modeling, management, logistics, optimization, research, strategy, operations",
    "International Journal of Complex Systems in Science":"complex, systems, science, modeling, simulation, dynamics, networks, nonlinear, interdisciplinary, research",
    "International Journal of Computational Methods":"computational, methods, algorithms, mathematics, simulation, modeling, applied, engineering, research, numerical",
    "International Journal of Computer Mathematics":"computer, mathematics, algorithms, numerical, applied, analysis, modeling, simulation, research, computation",
    "International Journal of Drug Policy":"drug, policy, health, public, research, addiction, regulation, society, treatment, prevention",
    "International Journal of Environmental Research and Public Health":"environment, health, public, research, epidemiology, pollution, risk, population, sustainability, policy",
    "International Journal of Geometric Methods in Modern Physics":"geometric, methods, physics, modern, mathematics, theory, relativity, quantum, research, analysis",
    "International Journal of Group Theory":"group, theory, algebra, mathematics, research, symmetry, structure, abstract, operations, finite",
    "International Journal of Heat and Mass Transfer":"heat, mass, transfer, thermal, fluid, convection, conduction, engineering, research, energy",
    "International Journal of Heat and Fluid Flow":"heat, fluid, flow, dynamics, turbulence, convection, engineering, research, simulation, transport",
    "International Journal of Information Technology & Decision Making":"information, technology, decision, making, systems, data, computing, analysis, research, management",
    "International Journal of Mathematics":"mathematics, research, analysis, algebra, geometry, applied, theory, topology, number, journal",
    "International Journal of Modern Physics A":"physics, modern, particles, quantum, field, theory, highenergy, research, symmetry, string",
    "International Journal of Modern Physics D":"physics, modern, cosmology, relativity, gravitation, astrophysics, dark, energy, universe, research",
    "International Journal of Sports Science & Coaching":"sports, science, coaching, training, performance, exercise, physiology, research, psychology, athletes",
    "International Journal of Strategic Property Management":"property, management, strategic, realestate, business, investment, planning, research, valuation, economics",
    "International Journal of Uncertainty Fuzziness and Knowledge Based Systems ...":"uncertainty, fuzziness, knowledge, systems, logic, modeling, decision, research, mathematics, theory",
    "International Mathematics Research Notices":"mathematics, research, notices, analysis, algebra, geometry, applied, theory, journal, number",
    "International communications in heat and mass transfer":"heat, mass, transfer, mechanics, thermodynamics, convection, nanofluids, rapid, research, communication",
    "International journal of pavement engineering":"pavement, engineering, road, durability, materials, design, construction, research, traffic, maintenance",
    "International journal of sports medicine":"sports, medicine, injury, performance, rehabilitation, research, physiology, training, athletes, orthopedics",
    "International transactions in operational research":"operations, research, optimization, modeling, algorithms, decision, analytics, strategy, systems, simulation",
    "Investigacion Operacional":"operations, research, Spain, optimization, modeling, logistics, decision, analysis, strategy, applied",
    "Investigacion bibliotecologica":"library, information, archivology, bibliotecology, research, communication, theory, Mexico, LIS, openaccess",
    "Investigaciones europeas de direccion y economia de la empresa":"management, economics, Europe, business, strategy, research, performance, leadership, policy, organizations",
    "Investigative Ophthalmology & Visual Science":"ophthalmology, vision, research, retina, imaging, clinical, glaucoma, disease, anatomy, physiology",
    "Iranian Journal of Fuzzy Systems":"fuzzy, systems, logic, uncertainty, control, modeling, research, applications, Iran, theory",
    "Israel Journal of Mathematics":"mathematics, research, Israel, pure, applied, algebra, analysis, geometry, theory, journal",
    "JMIR Medical Informatics":"informatics, medical, digital, health, data, research, ehealth, clinical, technology, journal",
    "JMIR Public Health and Surveillance":"publichealth, surveillance, epidemiology, digital, research, data, pandemic, informatics, monitoring, health",
    "JOSA A":"optics, JOSA, imaging, wave, research, physics, photonics, vision, theory, diffraction",
    "JOSA B":"optics, quantum, spectroscopy, lasers, photonics, nonlinear, research, JOSA, physics, science",
    "JP J.Geom.Topol.":"geometry, topology, mathematics, research, theory, manifolds, structure, algebraic, analysis, journal",
    "JP Journal of Geometry and Topology":"geometry, topology, mathematics, research, theory, manifolds, structure, algebraic, analysis, journal",
    "Journal d Analyse Mathematique":"analysis, mathematics, research, pure, theory, functional, integrals, geometry, topology, journal",
    "Journal de Mathematiques Pures et Appliquees":"mathematics, pure, applied, analysis, algebra, geometry, research, theory, PDE, journal",
    "Journal for the History of Astronomy":"astronomy, history, research, science, biography, culture, instruments, archives, astronomy, studies",
    "Journal fur die reine und angewandte Mathematik (Crelles Journal)":"mathematics, pure, applied, Crelle, research, theory, analysis, algebra, geometry, journal",
    "Journal of Algebra":"algebra, mathematics, research, theory, structures, groups, rings, modules, pure, applied",
    "Journal of Applied Analysis":"analysis, applied, differential, dynamics, optimization, functional, numerical, modelling, probability, geometry",
    "Journal of Applied Mathematics":"mathematics, applied, computational, industrial, research, modeling, numerical, engineering, algorithms, analysis",
    "Journal of Applied Mechanics":"mechanics, applied, engineering, mathematics, modeling, dynamics, continuum, materials, theory, research",
    "Journal of Applied Physics":"physics, applied, materials, experiments, optics, semiconductors, research, devices, theory, systems",
    "Journal of Approximation Theory":"approximation, theory, mathematics, functional, analysis, error, polynomial, convergence, research, algorithms",
    "Journal of Biological Systems":"biological, systems, modeling, mathematics, research, dynamics, complexity, ecology, theory, analysis",
    "Journal of Business Economics and Management":"business, economics, management, strategy, research, policy, finance, organizations, modeling, performance",
    "Journal of Catalan Studies":"Catalan, culture, language, history, research, literature, society, identity, studies, journal",
    "Journal of Classification":"classification, clustering, data, statistics, research, taxonomy, algorithms, analysis, modeling, methods",
    "Journal of Computational Biology":"computational, biology, modeling, genomics, bioinformatics, research, algorithms, systems, analysis, simulation",
    "Journal of Computational Methods in Science and Engineering":"computational, methods, science, engineering, algorithms, simulation, modeling, research, numerical, applications",
    "Journal of Computational and Applied Mathematics":"computational, applied, mathematics, algorithms, simulation, modeling, numerical, research, analysis, engineering",
    "Journal of Convex Analysis":"convex, analysis, optimization, functional, mathematics, geometry, variational, research, sets, theory",
    "Journal of Difference Equations and Applications":"difference, equations, discrete, applications, dynamics, modeling, mathematics, research, sequences, analysis",
    "Journal of Differential Equations":"differential, equations, PDE, research, analysis, dynamics, modeling, ordinary, functional, mathematics",
    "Journal of Dynamics and Differential Equations":"dynamics, differential, equations, systems, modeling, research, analysis, chaos, stability, mathematics",
    "Journal of Electronic Imaging":"electronic, imaging, image, processing, optics, algorithms, compression, analysis, research, systems",
    "Journal of Engineering Mathematics":"engineering, mathematics, modeling, analysis, applied, simulation, research, mechanics, computational, theory",
    "Journal of Evolution Equations":"evolution, equations, dynamics, partial, modeling, research, analysis, systems, time, mathematics",
    "Journal of Fluid Mechanics":"fluid, mechanics, dynamics, turbulence, modeling, research, experiments, flow, theory, simulation",
    "Journal of Fourier Analysis and Applications":"Fourier, analysis, harmonic, functions, transforms, applications, signal, research, mathematical, theory",
    "Journal of Function Spaces":"function, spaces, functional, analysis, Banach, Sobolev, mathematics, research, theory, topology",
    "Journal of Functional Analysis":"functional, analysis, mathematics, spaces, operators, theory, Banach, Hilbert, research, topology",
    "Journal of Geometry and Physics":"geometry, physics, mathematics, relativity, quantum, manifolds, gauge, differential, research, topology",
    "Journal of High Energy Physics":"physics, highenergy, particles, quantum, field, strings, collider, theory, symmetry, research",
    "Journal of Imaging Science and Technology":"imaging, science, technology, color, processing, vision, devices, digital, systems, research",
    "Journal of Industrial Engineering and Management (JIEM)":"industrial, engineering, management, logistics, production, operations, research, systems, optimization, business",
    "Journal of Inequalities and Applications":"inequalities, applications, mathematics, analysis, functional, convex, research, variational, optimization, theory",
    "Journal of Information Science Theory and Practice":"information, science, theory, practice, systems, knowledge, research, data, communication, digital",
    "Journal of Intelligent & Robotic Systems":"intelligent, robotic, systems, control, automation, sensors, algorithms, research, mechatronics, engineering",
    "Journal of Interdisciplinary Mathematics":"mathematics, interdisciplinary, applied, modeling, research, statistics, analysis, theory, probability, applications",
    "Journal of Mathematical Analysis and Applications":"mathematics, analysis, applications, research, functional, equations, differential, theory, modeling, numerical",
    "Journal of Mathematical Physics":"mathematics, physics, quantum, theory, differential, equations, geometry, research, operator, analysis",
    "Journal of Mathematical Sciences":"mathematics, sciences, research, applied, analysis, algebra, geometry, theory, probability, statistics",
    "Journal of Mathematics":"mathematics, research, analysis, algebra, geometry, applied, number, theory, topology, journal",
    "Journal of Modern Optics":"optics, modern, lasers, photonics, quantum, light, nonlinear, research, imaging, systems",
    "Journal of Non Crystalline Solids":"noncrystalline, solids, glass, materials, structure, amorphous, research, physical, properties, science",
    "Journal of Nonlinear Optical Physics & Materials":"nonlinear, optical, physics, materials, photonics, lasers, quantum, research, devices, properties",
    "Journal of Nonlinear and Convex Analysis":"nonlinear, convex, analysis, mathematics, optimization, functional, inequalities, theory, research, sets",
    "Journal of Open Innovation: Technology Market and Complexity":"innovation, technology, market, complexity, research, systems, management, entrepreneurship, science, open",
    "Journal of Operator Theory":"operator, theory, mathematics, functional, spaces, analysis, research, algebra, Hilbert, Banach",
    "Journal of Physics A: Mathematical and General":"physics, mathematical, general, theory, systems, research, quantum, classical, analysis, models",
    "Journal of Physics A: Mathematical and Theoretical":"physics, mathematical, theoretical, systems, quantum, research, models, classical, field, analysis",
    "Journal of Physics B: Atomic Molecular and Optical Physics":"physics, atomic, molecular, optical, quantum, lasers, spectroscopy, research, particles, interaction",
    "Journal of Physics D: Applied Physics":"physics, applied, materials, devices, optics, electronics, engineering, research, systems, energy",
    "Journal of Physics: Conference Series":"physics, conference, series, proceedings, research, applied, theoretical, experimental, multidisciplinary, science",
    "Journal of Pseudo-Differential Operators and Applications":"pseudo-differential, operators, analysis, applied, numerical, geometry, PDE, spectral, harmonic, quantum",
    "Journal of Pure and Applied Algebra":"algebra, theory, applied, pure, mathematics, rings, cohomology, research, applications, generalinterest",
    "Journal of Quantitative Spectroscopy and Radiative Transfer":"spectroscopy, radiative, spectroscopy, atmospheric, computational, modeling, light, plasma, atoms, remote-sensing",
    "Journal of Risk and Financial Management":"risk, finance, management, quantitative, modeling, economics, investments, research, policy, analysis",
    "Journal of Sound and Vibration":"sound, vibration, acoustics, dynamics, mechanical, analysis, modeling, research, structures, wave",
    "Journal of Spectral Theory":"spectral, theory, mathematics, operators, analysis, spectrum, research, functional, PDE, geometry",
    "Journal of Thoracic Oncology":"thoracic, oncology, cancer, diagnosis, treatment, epidemiology, multidisciplinary, research, lung, clinical",
    "Journal of Vibration and Acoustics":"vibration, acoustics, dynamics, mechanical, modeling, simulation, structural, sound, research, systems",
    "Journal of Visual Communication and Image Representation":"visual, communication, image, representation, processing, vision, multimedia, digital, theoretical, research",
    "Journal of biotechnology":"biotechnology, molecular, applied, research, fermentation, genetics, industrial, bioengineering, microbiology, technique",
    "Journal of molecular microbiology and biotechnology":"microbiology, molecular, biotechnology, bacteria, molecular, research, applied, genetics, fermentation, biotech",
    "Journal of the American Medical Informatics Association":"medical, informatics, digital, health, EMR, data, research, clinical, systems, technology",
    "Journal of the Association for Information Science and Technology":"information, science, technology, systems, library, digital, research, indexing, communication, knowledge",
    "Journal of the Australian Mathematical Society":"mathematics, research, Australia, pure, applied, theory, analysis, geometry, algebra, journal",
    "Journal of the London Mathematical Society":"mathematics, research, London, pure, applied, theory, algebra, analysis, geometry, community",
    "Journal of the Mathematical Society of Japan":"mathematics, research, Japan, pure, applied, theory, analysis, geometry, algebra, journal",
    "Journal of the Operational Research Society":"operations, research, decision, modeling, optimization, analytics, management, systems, logistics, theory",
    "Kossuth Lajos Tudomanyegyetem":"Hungary, university, education, research, teaching, academic, faculty, science, institution, engineering",
    "Kybernetika":"control, information, probability, decision, systems, optimization, AI, fuzziness, research, applied",
    "La Gaceta de la Real Sociedad Matematica Espanola":"mathematics, Spain, society, research, education, outreach, publication, community, articles, journal",
    "Laser & photonics reviews":"laser, photonics, optics, materials, devices, light, quantum, research, technology, nonlinear",
    "Lecture notes in pure and applied mathematics":"mathematics, pure, applied, lectures, series, research, analysis, algebra, geometry, theory",
    "Letters in Mathematical Physics":"mathematics, physics, quantum, relativity, algebra, geometry, research, models, theory, analysis",
    "Linear Algebra and its Applications":"linear, algebra, matrices, vectors, operators, spaces, theory, research, computation, applied",
    "Linear and Multilinear Algebra":"linear, multilinear, algebra, operators, spaces, theory, research, functional, analysis, tensor",
    "London Mathematical Society Lecture Notes Series":"mathematics, lectures, notes, research, society, analysis, algebra, geometry, topology, theory",
    "Mathematics Journal":"mathematics, research, analysis, algebra, geometry, applied, theory, number, topology, education",
    "Machine Learning":"machine, learning, algorithms, models, data, classification, prediction, research, neural, systems",
    "Matematicalia":"mathematics, Spain, education, outreach, articles, research, dissemination, teaching, communication, journal",
    "Matematicas: Ensenanza Universitaria":"mathematics, education, teaching, university, Spain, research, learning, didactics, pedagogy, academic",
    "Matematicki Vesnik":"mathematics, Serbia, research, algebra, analysis, geometry, applied, journal, society, theory",
    "Materials":"materials, science, engineering, properties, synthesis, structures, applications, devices, research, technology",
    "Math. Jpn":"mathematics, Japan, research, algebra, analysis, geometry, applied, theory, society, journal",
    "Mathematica Scandinavica":"mathematics, Scandinavia, research, algebra, analysis, geometry, applied, theory, journal, society",
    "Mathematical Foundations of Computing":"mathematics, computing, foundations, algorithms, complexity, theory, research, logic, data, systems",
    "Mathematical Inequalities & Applications":"inequalities, mathematics, applications, functional, convex, optimization, analysis, research, theory, sets",
    "Mathematical Inequalities and Applications":"inequalities, mathematics, applications, functional, convex, optimization, analysis, research, theory, sets",
    "Mathematical Methods in the Applied Sciences":"mathematics, methods, applied, sciences, modeling, analysis, research, equations, numerical, computation",
    "Mathematical Notes":"mathematics, notes, research, analysis, algebra, geometry, applied, theory, equations, journal",
    "Mathematical Problems in Engineering":"mathematical, problems, engineering, applied, modeling, systems, analysis, research, computation, optimization",
    "Mathematical Proceedings of the Cambridge Philosophical Society":"mathematics, Cambridge, research, algebra, analysis, geometry, topology, theory, applied, society",
    "Mathematical Programming":"mathematical, programming, optimization, algorithms, modeling, operations, research, computation, applied, theory",
    "Mathematical Research Letters":"mathematics, research, letters, algebra, analysis, geometry, topology, applied, theory, publication",
    "Mathematical and Computer Modelling":"mathematical, computer, modelling, simulation, applied, algorithms, systems, research, analysis, computation",
    "Mathematics Magazine":"mathematics, education, teaching, college, research, exposition, articles, problem, learning, pedagogy",
    "Mathematics and Mechanics of Solids":"mathematics, mechanics, solids, materials, structures, elasticity, plasticity, fracture, research, modeling",
    "Mathematische Annalen":"mathematics, analysis, algebra, geometry, topology, theory, research, pure, applied, journal",
    "Mathematische Nachrichten":"mathematics, research, analysis, algebra, geometry, topology, functional, theory, applied, journal",
    "Mathematische Zeitschrift":"mathematics, research, algebra, geometry, analysis, topology, number, theory, pure, applied",
    "Mechanical Systems and Signal Processing":"mechanical, systems, signal, processing, vibration, noise, dynamics, monitoring, analysis, engineering",
    "Medicina Clinica":"medicine, clinical, Spain, healthcare, diagnosis, treatment, research, epidemiology, practice, hospital",
    "Mediterranean Journal of Mathematics":"mathematics, Mediterranean, research, analysis, algebra, geometry, topology, applied, theory, journal",
    "Metabolites":"metabolites, metabolism, biology, pathways, biomarkers, biochemistry, analysis, research, health, disease",
    "Metabolites. Basel. Vol.":"metabolites, Basel, metabolism, pathways, biomarkers, biology, research, analysis, health, biochemistry",
    "MethodsX":"methods, science, openaccess, reproducibility, experimental, protocols, interdisciplinary, research, applied, innovation",
    "Michigan Mathematical Journal":"mathematics, Michigan, research, algebra, geometry, analysis, topology, theory, applied, journal",
    "MODELLING FOR ADDICTIVE BEHAVIOUR MEDICINE AND ENGINEERING":"modelling, addictive, behaviour, medicine, engineering, systems, research, health, analysis, simulation",
    "Modelling in Science Education and Learning":"modelling, science, education, learning, teaching, research, pedagogy, simulation, mathematics, methods",
    "Modern Physics Letters A":"physics, modern, particles, quantum, field, strings, collider, theory, symmetry, research",
    "Monatshefte fur Mathematik":"mathematics, research, algebra, geometry, analysis, topology, number, theory, pure, applied",
    "Monografie Matematyczne":"mathematics, monograph, Poland, research, analysis, algebra, geometry, applied, theory, topology",
    "Montes Taurus Journal of Pure and Applied Mathematics":"mathematics, pure, applied, research, algebra, geometry, analysis, theory, topology, journal",
    "Monthly Notices of the Royal Astronomical Society":"astronomy, astrophysics, cosmology, galaxies, stars, blackholes, relativity, physics, space, research",
    "Nagoya Mathematical Journal":"mathematics, Nagoya, research, analysis, algebra, geometry, topology, theory, applied, journal",
    "Nature":"science, multidisciplinary, research, biology, physics, chemistry, environment, medicine, innovation, journal",
    "Neural Computing and Applications":"neural, computing, applications, machinelearning, algorithms, systems, optimization, research, networks, data",
    "Neurocomputing":"neurocomputing, neural, networks, artificial, intelligence, algorithms, machinelearning, models, research, systems",
    "New Journal of Physics":"neurocomputing, neural, networks, artificial, intelligence, algorithms, machinelearning, models, research, systems",
    "New biotechnology":"biotechnology, innovation, genetics, molecular, bioengineering, research, applied, health, industrial, science",
    "Nonlinear Analysis: Theory Methods & Applications":"nonlinear, analysis, theory, methods, applications, mathematics, equations, variational, research, dynamics",
    "Nonlinear Dynamics":"nonlinear, dynamics, systems, chaos, stability, modeling, oscillations, bifurcations, research, mathematics",
    "North-Holland Mathematics Studies":"mathematics, studies, research, analysis, algebra, geometry, topology, applied, theory, NorthHolland",
    "Note di Matematica":"mathematics, studies, research, analysis, algebra, geometry, topology, applied, theory, NorthHolland",
    "Nuclear Instruments and Methods in Physics Research Section A: Accelerators":"nuclear, instruments, methods, physics, accelerators, detectors, particles, research, radiation, experimental",
    "Numerical Heat Transfer: Part B: Fundamentals":"nuclear, instruments, methods, physics, accelerators, detectors, particles, research, radiation, experimental",
    "Oberwolfach Reports":"mathematics, reports, Oberwolfach, conferences, research, analysis, algebra, geometry, topology, applied",
    "Open Mathematics":"mathematics, openaccess, research, analysis, algebra, geometry, applied, theory, journal, probability",
    "Open Problems in the Geometry and Analysis of Banach Spaces":"problems, geometry, analysis, Banach, spaces, functional, research, theory, mathematics, topology",
    "Operational Research":"operations, research, optimization, decision, modeling, algorithms, logistics, systems, applied, management",
    "Operator Theory: Advances and Applications":"operator, theory, mathematics, functional, spaces, Banach, Hilbert, analysis, research, applications",
    "Operators and Matrices":"operators, matrices, linear, algebra, theory, spectral, research, analysis, mathematics, functional",
    "Opt. Lett.":"optics, letters, light, lasers, photonics, imaging, quantum, nonlinear, research, devices",
    "Optica pura y aplicada. Revista en espanol de optica y fotonica":"optics, photonics, Spain, applied, pure, research, light, imaging, lasers, devices",
    "Optics Express":"optics, express, photonics, lasers, imaging, vision, quantum, nonlinear, research, devices",
    "Optics Letters":"optics, letters, lasers, photonics, imaging, nonlinear, quantum, research, devices, vision",
    "PASOS Revista de Turismo y Patrimonio Cultural":"tourism, heritage, culture, Spain, research, management, history, travel, society, patrimony",
    "PH: Boletin del Instituto Andaluz del Patrimonio Historico":"heritage, Andalusia, history, Spain, patrimony, preservation, culture, research, conservation, art",
    "PROFESIONAL DE LA INFORMACION":"information, documentation, research, Spain, libraries, communication, knowledge, digital, management, journal",
    "Pacific journal of mathematics":"mathematics, Pacific, research, analysis, algebra, geometry, topology, applied, theory, journal",
    "Pain Practice":"pain, practice, medicine, clinical, management, treatment, therapy, research, health, patients",
    "Pattern Recognition Letters":"pattern, recognition, machinelearning, vision, image, classification, algorithms, data, analysis, research",
    "Pediatria Atencion Primaria":"pediatrics, primary, healthcare, children, clinical, medicine, Spain, diagnosis, treatment, research",
    "Perfiles latinoamericanos":"LatinAmerica, social, politics, economics, society, culture, research, sociology, policy, studies",
    "Periodica Mathematica Hungarica":"mathematics, Hungary, research, algebra, geometry, analysis, topology, applied, theory, journal",
    "Phononics":"phononics, phonons, thermal, materials, acoustic, vibrations, energy, research, transport, metamaterials",
    "Photonics and Nanostructures Fundamentals and Applications":"photonics, nanostructures, optics, fundamentals, applications, light, quantum, devices, research, materials",
    "Physica D: Nonlinear Phenomena":"physica, nonlinear, phenomena, dynamics, chaos, complexity, systems, modeling, mathematics, physics",
    "Physica Scripta":"physics, experimental, theoretical, atomic, molecular, quantum, plasma, research, applied, nuclear",
    "Physical Acoustics":"acoustics, physical, sound, waves, propagation, vibrations, ultrasound, research, materials, theory",
    "Physical Review Applied":"physics, applied, devices, materials, engineering, optics, electronics, research, quantum, energy",
    "Physical Review Letters":"physics, letters, rapid, communication, quantum, condensed, particles, nuclear, optics, research",
    "Physics Letters A":"physics, letters, applied, theoretical, condensed, matter, particles, quantum, research, communication",
    "Physics Procedia":"physics, proceedings, conference, applied, experimental, theoretical, research, multidisciplinary, science, papers",
    "Physics Reports":"physics, reports, review, theoretical, experimental, quantum, condensed, particles, nuclear, research",
    "Planetary and Space Science":"planetary, space, science, astronomy, geology, physics, atmosphere, solar, research, systems",
    "PloS one":"science, multidisciplinary, openaccess, biology, medicine, research, health, environment, data, articles",
    "Portugaliae Mathematica":"mathematics, Portugal, research, analysis, algebra, geometry, topology, applied, theory, journal",
    "Positivity":"positivity, mathematics, analysis, functional, Banach, spaces, theory, research, operators, applied",
    "Procedia Computer Science":"computer, science, proceedings, conference, applied, research, algorithms, systems, computing, data",
    "Proceedings of Meetings on Acoustics":"acoustics, meetings, proceedings, conference, sound, research, vibration, speech, applied, noise",
    "Proceedings of Science":"proceedings, science, conference, physics, astronomy, meetings, multidisciplinary, research, reports, papers",
    "Proceedings of the AMS":"mathematics, proceedings, AMS, research, analysis, algebra, geometry, topology, number, applied",
    "Proceedings of the Edinburgh Mathematical Society":"mathematics, Edinburgh, society, research, algebra, analysis, geometry, topology, applied, theory",
    "Proceedings of the Institute of Mathematics and Mechanics":"mathematics, mechanics, research, analysis, algebra, geometry, theory, applied, systems, journal",
    "Proceedings of the Institution of Mechanical Engineers Part M: Journal of":"mechanical, engineers, systems, design, materials, applications, modeling, structures, industry, research",
    "Proceedings of the London Mathematical Society":"mathematics, London, society, research, analysis, algebra, geometry, topology, number, theory",
    "Proceedings of the National Academy of Sciences":"science, multidisciplinary, biology, physics, chemistry, environment, health, research, innovation, USA",
    "Proceedings of the Royal Society A":"physics, mathematics, chemistry, engineering, theoretical, applied, research, society, multidisciplinary, journal",
    "Proceedings of the Royal Society of Edinburgh Section A: Mathematics":"mathematics, Edinburgh, research, analysis, algebra, geometry, topology, applied, theory, society",
    "Proceedings-Mathematical Sciences":"mathematics, research, analysis, algebra, geometry, topology, applied, theory, equations, journal",
    "Progress of Theoretical Physics Supplement":"physics, theoretical, supplement, quantum, particles, fields, relativity, research, models, mathematics",
    "Psychologica Belgica":"psychology, Belgium, research, cognition, behavior, social, clinical, experimental, education, science",
    "Publ. Math. Debrecen":"mathematics, Debrecen, research, analysis, algebra, geometry, topology, applied, theory, journal",
    "Publicacions Matematiques":"mathematics, Spain, research, algebra, analysis, geometry, topology, applied, theory, journal",
    "Publications of the Astronomical Society of the Pacific":"astronomy, astrophysics, telescopes, instruments, stars, galaxies, solar, space, research, observations",
    "Publications of the Research Institute for Mathematical Sciences":"mathematics, research, analysis, algebra, geometry, topology, functional, theory, applied, RIMS",
    "Quaderns de Filosofia i Ciencia":"philosophy, science, Catalonia, research, epistemology, history, culture, theory, knowledge, society",
    "Quaestiones Mathematicae":"mathematics, research, algebra, analysis, geometry, topology, theory, applied, equations, journal",
    "Quality & Quantity":"quality, quantity, social, research, methodology, statistics, data, analysis, sociology, measurement",
    "Quarterly Journal of Mathematics":"mathematics, research, analysis, algebra, geometry, topology, number, applied, theory, journal",
    "Quodons in Mica: Nonlinear Localized Travelling Excitations in Crystals":"nonlinear, localized, excitations, crystals, mica, physics, vibrations, traveling, research, materials",
    "REDU. Revista de Docencia Universitaria":"education, university, teaching, Spain, pedagogy, research, learning, curriculum, higher, didactics",
    "REVISTA ESPANOLA DE DOCUMENTACION CIENTIFICA":"documentation, science, Spain, research, bibliometrics, information, libraries, knowledge, journals, communication",
    "REVISTA ORL":"otolaryngology, clinical, Spain, medicine, ENT, research, diagnosis, treatment, surgery, health",
    "Real Academia de Ciencias":"science, Spain, academy, research, mathematics, physics, chemistry, biology, history, publications",
    "Real Estate Management and Valuation":"realestate, management, valuation, economics, finance, property, investment, business, research, strategy",
    "Real Time Imaging":"imaging, realtime, processing, vision, medical, computer, analysis, algorithms, research, technology",
    "Rendiconti LinceiMatematica e Applicazioni":"mathematics, Italy, research, analysis, algebra, geometry, topology, applied, theory, journal",
    "Rendiconti del Circolo Matematico di Palermo":"mathematics, Palermo, research, analysis, algebra, geometry, topology, applied, theory, journal",
    "Rendiconti del Seminario Matematico della Universita di Padova":"mathematics, Padova, research, analysis, algebra, geometry, topology, applied, theory, journal",
    "Research evaluation":"research, evaluation, policy, science, impact, institutions, funding, management, analysis, innovation",
    "Research in Transportation Business & Management":"transportation, business, management, logistics, mobility, research, operations, policy, supply, systems",
    "Results Math":"mathematics, results, research, analysis, algebra, geometry, topology, applied, theory, journal",
    "Results in Engineering":"engineering, results, research, design, systems, applications, modeling, innovation, technology, applied",
    "Results in Mathematics":"mathematics, results, research, analysis, algebra, geometry, topology, applied, theory, journal",
    "Rev. R. Academia de Ciencias de Madrid":"science, Spain, academy, research, mathematics, physics, chemistry, biology, history, Madrid",
    "Rev. Tec. Ing. LUZ":"engineering, technology, Venezuela, research, university, innovation, design, systems, applied, science",
    "Rev. chil. cir":"surgery, Chile, clinical, medicine, research, health, treatment, hospital, practice, patients",
    "Revista Clinica Espanola":"medicine, clinical, Spain, healthcare, research, hospital, diagnosis, treatment, epidemiology, practice",
    "Revista Colombiana de Matematicas":"mathematics, Colombia, research, analysis, algebra, geometry, topology, applied, theory, journal",
    "Revista Cubana de Fisica":"physics, Cuba, research, theoretical, experimental, education, applied, science, journal, community",
    "Revista de Senologia y Patologia Mamaria":"senology, pathology, breast, cancer, clinical, Spain, diagnosis, treatment, research, health",
    "Revista Espanola de Estudios Agrosociales y Pesqueros":"Spain, agriculture, fisheries, economics, policy, rural, research, environment, management, society",
    "Revista Forestal Baracoa":"forestry, Cuba, research, environment, management, ecosystems, resources, biodiversity, rural, journal",
    "Revista Iberoamericana de Sistemas Cibernetica en Informatica":"systems, cybernetics, informatics, Iberoamerica, research, modeling, computing, theory, applied, communication",
    "Revista Iberoamericana de Automatica e Informatica industrial":"automation, informatics, industrial, Iberoamerica, research, control, systems, robotics, applied, technology",
    "Revista Matematica Complutense":"mathematics, Spain, Complutense, research, analysis, algebra, geometry, topology, applied, theory",
    "Revista Matematica Hispanoamericana":"mathematics, Hispanoamerica, research, analysis, algebra, geometry, topology, applied, theory, journal",
    "Revista Matematica Iberoamericana":"mathematics, Iberoamerica, research, analysis, algebra, geometry, topology, applied, theory, journal",
    "Revista PH":"heritage, Andalusia, history, Spain, preservation, culture, architecture, research, patrimony, conservation",
    "Revista de Acustica":"acoustics, sound, noise, vibration, Spain, engineering, environment, research, waves, applied",
    "Revista de Contabilidad":"accounting, Spain, finance, auditing, management, economics, research, reporting, analysis, business",
    "Revista de Contabilidad y Tributacion. CEF":"accounting, taxation, Spain, finance, law, auditing, management, research, reporting, business",
    "Revista de Contabilidad-Spanish Accounting Review":"accounting, Spanish, finance, auditing, reporting, economics, management, research, transparency, business",
    "Revista de Economia Publica Social y Cooperativa":"economics, public, social, cooperative, policy, Spain, research, management, finance, organizations",
    "Revista de Estudios Empresariales. Segunda Epoca":"business, management, Spain, enterprises, economics, strategy, research, organizations, policy, education",
    "Revista de economia financiera":"finance, economics, Spain, markets, banking, investment, policy, research, management, business",
    "Revista de estudios regionales":"regional, studies, economics, Spain, geography, policy, research, planning, development, management",
    "Revista de la Academia Canaria de Ciencias":"science, Canary, Spain, research, biology, physics, mathematics, culture, academy, natural",
    "Revista de la Real Academia de Ciencias Exactas Fisicas y Naturales. Serie":"science, Spain, academy, mathematics, physics, chemistry, natural, research, history, publications",
    "Revista espanola de cardiologia":"cardiology, Spain, medicine, clinical, research, heart, diagnosis, treatment, hospital, health",
    "Revista espanola de fisica":"physics, Spain, research, education, society, experimental, theoretical, applied, community, journal",
    "Revista europea de direccion y economia de la empresa":"business, management, Europe, economics, research, enterprises, finance, policy, strategy, organizations",
    "Revista general de informacion y documentacion":"information, documentation, Spain, research, libraries, communication, knowledge, archives, digital, management",
    "Revista internacional de transparencia e integridad":"transparency, integrity, ethics, Spain, law, research, governance, accountability, policy, society",
    "Revista matematica de la Universidad Complutense de Madrid":"mathematics, Spain, Complutense, research, analysis, algebra, geometry, topology, applied, theory",
    "Revista mexicana de fisica":"physics, Mexico, research, experimental, theoretical, applied, education, community, journal, science",
    "Revista valenciana destudis autonomics":"Valencia, Spain, regional, policy, autonomy, research, governance, law, society, administration",
    "Rocky Mountain Journal of Mathematics":"mathematics, RockyMountain, research, analysis, algebra, geometry, topology, applied, theory, journal",
    "Royal Irish Academy":"academy, Ireland, science, research, humanities, culture, history, mathematics, publications, society",
    "SAE Technical Paper":"engineering, automotive, SAE, technology, design, systems, research, mechanics, vehicles, innovation",
    "SAGE Publications":"publisher, academic, journals, books, research, multidisciplinary, education, science, humanities, social",
    "SCMNoticies":"news, SCM, mathematics, society, Spain, research, publications, communication, bulletin, community",
    "SEDIC":"documentation, information, Spain, society, libraries, archives, research, science, digital, management",
    "SIGMA. Symmetry Integrability and Geometry: Methods and Applications":"symmetry, integrability, geometry, methods, applications, mathematics, analysis, theory, algebra, research",
    "SPE Latin America and Caribbean Petroleum Engineering Conference SPE":"petroleum, engineering, conference, LatinAmerica, Caribbean, oil, gas, energy, technology, research",
    "SPIE Photonics West":"photonics, optics, lasers, imaging, devices, conference, SPIE, light, research, technology",
    "SSRN":"social, science, research, network, economics, law, finance, management, openaccess, papers",
    "Scandinavian journal of psychology":"psychology, Scandinavian, cognition, behavior, research, clinical, experimental, social, mental, education",
    "Science Advances":"science, multidisciplinary, research, biology, physics, chemistry, health, innovation, environment, technology",
    "Scientific Reports":"science, multidisciplinary, research, openaccess, biology, medicine, physics, chemistry, environment, data",
    "Scientometrics":"scientometrics, bibliometrics, research, evaluation, publications, science, indicators, analysis, impact, knowledge",
    "Scire: Representacion y organizacion del conocimiento":"knowledge, representation, organization, information, Spain, research, communication, libraries, science, management",
    "Semigroup Forum":"semigroups, algebra, mathematics, structures, research, abstract, applied, theory, analysis, operations",
    "Sensors":"sensors, devices, measurement, systems, electronics, technology, applications, research, engineering, data",
    "Service Business":"service, business, management, strategy, research, marketing, innovation, economics, performance, organizations",
    "Servicio Editorial de la Universidad del Pais Vasco/Euskal Herriko":"publisher, university, Spain, Basque, academic, research, books, journals, education, editorial",
    "Set Valued Analysis":"set, valued, analysis, optimization, mathematics, convex, functions, research, applications, theory",
    "Shock and Vibration":"shock, vibration, dynamics, mechanical, engineering, materials, research, noise, structures, systems",
    "Signal Image and Video Processing":"signal, image, video, processing, vision, algorithms, multimedia, research, systems, computing",
    "Signal Processing":"signal, processing, algorithms, data, audio, image, vision, research, communication, systems",
    "Situacion y tendencias de la contabilidad de gestion en el ambito":"accounting, management, trends, Spain, research, finance, business, control, reporting, organizations",
    "Sociedad Espanola de Investigacion en Educacion Matematica":"mathematics, education, Spain, society, teaching, learning, pedagogy, didactics, research, community",
    "Solitons & Fractals":"solitons, fractals, nonlinear, dynamics, chaos, complexity, mathematics, modeling, research, physics",
    "South African Journal of Science":"science, multidisciplinary, SouthAfrica, research, biology, physics, chemistry, environment, society, innovation",
    "Southeast Asian Bulletin of Mathematics":"mathematics, SoutheastAsia, research, analysis, algebra, geometry, topology, applied, theory, journal",
    "Spinal cord":"spinal, cord, medicine, injury, neuroscience, rehabilitation, research, clinical, health, therapy",
    "Structural and Multidisciplinary Optimization":"structural, multidisciplinary, optimization, engineering, design, modeling, research, systems, simulation, mechanics",
    "Structures":"structures, engineering, construction, materials, design, mechanics, research, modeling, simulation, systems",
    "Studia Math":"mathematics, research, analysis, algebra, geometry, topology, functional, applied, theory, journal",
    "Studia Psychologica":"psychology, cognition, behavior, research, social, clinical, experimental, mental, education, science",
    "Studia Scientiarum Mathematicarum Hungarica":"mathematics, Hungary, research, analysis, algebra, geometry, topology, applied, theory, journal",
    "Studies of Applied Economics":"mathematics, Hungary, research, analysis, algebra, geometry, topology, applied, theory, journal",
    "Suma":"mathematics, Spain, education, teaching, learning, didactics, research, pedagogy, university, journal",
    "Sustainability":"sustainability, environment, policy, economics, society, energy, research, management, climate, development",
    "Symmetry":"symmetry, mathematics, physics, invariance, geometry, group, quantum, research, theory, applications",
    "TU Delft":"university, Delft, Netherlands, research, engineering, technology, science, education, innovation, academic",
    "Taiwanese Journal of Mathematics":"mathematics, Taiwan, research, analysis, algebra, geometry, topology, applied, theory, journal",
    "Tarbiya Revista de Investigacion e Innovacion Educativa":"education, innovation, teaching, learning, research, pedagogy, Spain, didactics, curriculum, university",
    "Technium Soc. Sci. J.":"social, sciences, research, multidisciplinary, policy, management, society, education, economics, communication",
    "Technological and Economic Development of Economy":"technology, economic, development, economy, innovation, management, policy, research, business, strategy",
    "The American Mathematical Monthly":"mathematics, monthly, exposition, education, problem, teaching, research, analysis, algebra, geometry",
    "The Astronomical Journal":"astronomy, astrophysics, stars, galaxies, planets, solar, space, research, observation, cosmology",
    "The European Physical Journal C":"physics, particles, highenergy, collider, quantum, field, symmetry, theory, research, CERN",
    "The European Physical Journal D":"physics, atomic, molecular, optical, quantum, lasers, spectroscopy, research, particles, interaction",
    "The European Physical Journal Special Topics":"physics, special, topics, interdisciplinary, research, applied, theory, experiments, multidisciplinary, review",
    "The Journal of Geometric Analysis":"geometry, analysis, mathematics, differential, topology, manifolds, algebraic, research, theory, applied",
    "The Journal of the Acoustical Society of America":"acoustics, sound, vibration, waves, speech, hearing, noise, research, analysis, applied",
    "The Physics Teacher":"physics, education, teaching, learning, pedagogy, research, classroom, experiments, curriculum, methods",
    "The Quarterly Journal of Mathematics":"mathematics, quarterly, research, analysis, algebra, geometry, topology, applied, number, theory",
    "The Rocky Mountain Journal of Mathematics":"mathematics, RockyMountain, research, analysis, algebra, geometry, topology, applied, theory, journal",
    "The journal of physical chemistry letters":"chemistry, physical, quantum, spectroscopy, molecular, materials, nanoscience, research, energy, reactions",
    "Theoria: An International Journal for Theory History and Foundations of":"theory, history, philosophy, science, epistemology, logic, research, knowledge, foundations, studies",
    "Thermal Science":"thermal, science, heat, energy, transfer, combustion, fluids, research, modeling, engineering",
    "Top":"mathematics, topology, analysis, geometry, research, theory, algebra, applied, journal, structures",
    "Topology":"topology, mathematics, research, manifolds, geometry, analysis, algebraic, theory, spaces, journal",
    "Topology and its Applications":"topology, applications, mathematics, analysis, geometry, manifolds, algebraic, research, spaces, theory",
    "Transactions of the American Mathematical Society":"mathematics, AMS, research, analysis, algebra, geometry, topology, applied, number, theory",
    "Turkish Journal of Mathematics":"mathematics, Turkey, research, algebra, analysis, geometry, topology, applied, theory, journal",
    "US Patent App.":"patent, application, US, invention, innovation, intellectual, property, research, technology, protection",
    "Ukrainian Journal of Physics":"physics, Ukraine, research, theoretical, experimental, quantum, particles, condensed, nuclear, applied",
    "Universe":"universe, astronomy, cosmology, astrophysics, relativity, quantum, galaxies, space, research, physics",
    "Universidad Nacional de Educacion a Distancia. Departamento de Matematicas":"university, Spain, UNED, mathematics, education, distance, research, teaching, applied, academic",
    "Universidad Politecnica de Valencia":"university, Spain, Valencia, engineering, technology, research, education, innovation, science, academic",
    "Universidad de Alicante":"university, Spain, Alicante, education, research, teaching, science, academic, publications, faculty",
    "Universidad de Extremadura Servicio de Publicaciones":"university, Spain, Extremadura, publications, editorial, academic, research, education, books, journals",
    "Universidad de Murcia":"university, Spain, Murcia, education, research, teaching, academic, science, faculty, publications",
    "Universidad de Oviedo":"university, Spain, Oviedo, education, research, academic, science, teaching, publications, faculty",
    "Universidad nacional de educacion a distancia":"university, Spain, UNED, education, distance, research, teaching, science, academic, publications",
    "Universita degli Studi di Trieste. Dipartimento di Scienze Matematiche":"university, Italy, Trieste, mathematics, department, education, research, academic, science, faculty",
    "Universitat Politecnica de Valencia":"university, Spain, Valencia, engineering, technology, research, education, innovation, science, academic",
    "Universitat Ramon Llull":"university, Spain, RamonLlull, education, research, teaching, academic, science, publications, faculty",
    "Universitat de Barcelona":"university, Spain, Barcelona, education, research, academic, science, teaching, publications, faculty",
    "Universitat de Girona. Institut de Ciencies de l'Educacio Josep Pallach":"university, Spain, Girona, education, institute, research, teaching, pedagogy, science, faculty",
    "Universitat de Valencia":"university, Spain, Valencia, education, research, academic, teaching, science, publications, faculty",
    "Universitatsbibliothek der RWTH Aachen":"university, Germany, Aachen, library, publications, research, education, science, resources, academic",
    "University of Helsinki. Department of Mathematics":"university, Finland, Helsinki, mathematics, department, research, education, academic, science, faculty",
    "University of Nis":"university, Serbia, Nis, education, research, mathematics, science, academic, faculty, teaching",
    "University of Sistan and Baluchestan":"university, Iran, Sistan, Baluchestan, education, research, academic, faculty, science, teaching",
    "Uno: Revista de didactica de las matematicas":"mathematics, didactics, education, teaching, learning, pedagogy, Spain, research, curriculum, school",
    "Updated and Expanded":"updated, expanded, edition, publication, research, revised, science, knowledge, academic, books",
    "Valencia: CSIC Generalitat Valenciana":"CSIC, Valencia, Spain, research, science, government, publications, academy, innovation, education",
    "Vietnam Journal of Mathematics":"mathematics, Vietnam, research, analysis, algebra, geometry, topology, applied, theory, journal",
    "Vilnius Gediminas Technical University":"university, Lithuania, Vilnius, engineering, technology, research, academic, science, education, innovation",
    "Vilnius University":"university, Lithuania, Vilnius, education, research, academic, faculty, science, history, teaching",
    "Viscoelastic and Viscoplastic Materials":"viscoelastic, viscoplastic, materials, mechanics, deformation, polymers, research, modeling, engineering, properties",
    "WIT Transactions on Engineering Sciences":"engineering, sciences, WIT, transactions, research, applied, technology, design, modeling, innovation",
    "WO Patent":"patent, WO, innovation, intellectual, property, application, technology, research, protection, invention",
    "WPOM-Working Papers on Operations Management":"operations, management, workingpapers, logistics, business, strategy, research, modeling, systems, decision",
    "Walter de Gruyter":"publisher, academic, research, journals, books, Germany, science, humanities, education, editorial",
    "Walter de Gruyter GmbH & Co. KG":"publisher, Germany, academic, research, books, journals, science, humanities, education, editorial",
    "Wave Motion":"wave, motion, dynamics, mechanics, physics, propagation, modeling, systems, vibrations, research",
    "Waves":"waves, physics, propagation, acoustics, water, systems, vibrations, dynamics, modeling, research",
    "Waves in Random and Complex Media":"waves, random, complex, media, propagation, scattering, physics, modeling, research, dynamics",
    "Wiadomosci Matematyczne":"mathematics, Poland, research, analysis, algebra, geometry, topology, applied, theory, journal",
    "Wiley Liss Inc.":"publisher, Wiley, academic, research, journals, books, science, education, medicine, editorial",
    "Wiley VCH Verlag":"publisher, Wiley, VCH, Germany, research, journals, books, science, chemistry, editorial",
    "World Scientific Publishing Co. Pte Ltd":"publisher, Singapore, research, academic, journals, books, science, technology, mathematics, editorial",
    "Zeitschrift fur Analysis und ihre Anwendungen":"analysis, mathematics, applications, research, functional, algebra, geometry, theory, topology, journal",
    "Zeitschrift fur Physik A Hadrons and Nuclei":"physics, hadrons, nuclei, particles, nuclear, quantum, research, scattering, experimental, theory",
    "Zeitschrift fur Physik C Particles and Fields":"physics, particles, fields, quantum, highenergy, collider, theory, research, symmetry, experimental",
    "Zeta functions in algebra and geometry. Contemp. Math":"zeta, functions, algebra, geometry, mathematics, number, theory, analysis, research, topology",
    "eurasian journal of mathematical and computer applications":"mathematics, computer, applications, Eurasia, algorithms, modeling, research, simulation, applied, systems",
    "international journal of hydrogen energy":"hydrogen, energy, renewable, fuel, cells, research, combustion, storage, technology, applications",
    "manuscripta mathematica":"mathematics, research, algebra, analysis, geometry, topology, number, theory, applied, journal"
}

nombre_archivo_csv = "One_Hot_Palabras_Revistas.xlsx"
crear_one_hot_excel(dic, nombre_archivo_csv)